import { Exercise, TrainingDay, WeekMenu } from "@/types";

// ─── Exercise Library ─────────────────────────────────────────────────────────
export const EXERCISES: Exercise[] = [
  {
    id: "bird-dog",
    name: "Bird Dog",
    nameEs: "Perro Pájaro",
    category: "core",
    sets: 3,
    reps: 8,
    description: "Fortalece el core profundo y estabiliza la columna sin compresión lumbar. Es el ejercicio #1 para espondilolistesis.",
    steps: [
      "Colócate en cuatro apoyos: manos bajo hombros, rodillas bajo caderas.",
      "Mantén la espalda neutra, abdomen ligeramente contraído.",
      "Extiende el brazo derecho hacia adelante y la pierna izquierda hacia atrás simultáneamente.",
      "Mantén la posición 3–5 segundos sin rotar las caderas.",
      "Regresa lentamente y alterna el lado.",
    ],
    muscles: ["Multífidos", "Transverso abdominal", "Glúteo mayor", "Deltoides"],
    imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=700&q=80&fit=crop",
    safeForL5S1: true,
    notes: "No arquear la zona lumbar. Las caderas deben permanecer paralelas al suelo.",
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    nameEs: "Insecto Muerto",
    category: "core",
    sets: 3,
    reps: 10,
    description: "Activa el transverso abdominal, el músculo profundo que estabiliza la columna.",
    steps: [
      "Acuéstate boca arriba con brazos apuntando al techo y rodillas a 90°.",
      "Presiona la espalda baja contra el suelo: esto es fundamental.",
      "Lentamente baja el brazo derecho al suelo y la pierna izquierda hasta casi tocar.",
      "Mantén 2 segundos, regresa y alterna.",
    ],
    muscles: ["Transverso abdominal", "Recto abdominal", "Oblicuos", "Iliopsoas"],
    imageUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=700&q=80&fit=crop",
    safeForL5S1: true,
    notes: "La espalda baja SIEMPRE pegada al suelo. Si se despega, reduce el rango de movimiento.",
  },
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    nameEs: "Puente de Glúteos",
    category: "core",
    sets: 3,
    reps: 12,
    description: "Glúteos fuertes = menos carga lumbar. Cuando los glúteos son débiles, la espalda compensa todo el trabajo.",
    steps: [
      "Acostado boca arriba, rodillas dobladas, pies apoyados a ancho de caderas.",
      "Contrae el abdomen y empuja el suelo con los talones.",
      "Eleva la cadera hasta que el cuerpo forme una línea diagonal.",
      "Aprieta los glúteos arriba y mantén 2 segundos.",
      "Baja lentamente.",
    ],
    muscles: ["Glúteo mayor", "Isquiotibiales", "Core", "Erectores espinales"],
    imageUrl: "https://images.unsplash.com/photo-1604480132736-44c188fe4d20?w=700&q=80&fit=crop",
    safeForL5S1: true,
  },
  {
    id: "side-plank",
    name: "Side Plank",
    nameEs: "Plancha Lateral",
    category: "core",
    sets: 3,
    duration: 25,
    description: "Fortalece el core lateral que protege la columna. Empieza con rodillas apoyadas si es necesario.",
    steps: [
      "Apóyate en el codo derecho (directamente bajo el hombro) y en el pie/rodilla derecha.",
      "Eleva la cadera formando una línea recta de cabeza a pies.",
      "Abdomen contraído, no dejes que la cadera caiga.",
      "Mantén el tiempo indicado y cambia de lado.",
    ],
    muscles: ["Oblicuo externo", "Glúteo medio", "Cuadrado lumbar", "Core lateral"],
    imageUrl: "https://images.unsplash.com/photo-1549060279-7e168fcee0c2?w=700&q=80&fit=crop",
    safeForL5S1: true,
    notes: "Comenzar con rodillas apoyadas. Progresar a piernas extendidas.",
  },
  {
    id: "hip-thrust",
    name: "Hip Thrust",
    nameEs: "Empuje de Cadera",
    category: "strength",
    sets: 3,
    reps: 12,
    description: "El ejercicio de glúteos más efectivo. Glúteos fuertes reducen drásticamente la carga en L5-S1.",
    steps: [
      "Apoya la espalda alta en un banco o sofá, pies apoyados en el suelo.",
      "Baja la cadera hacia el suelo.",
      "Empuja con los talones y sube la cadera apretando los glúteos.",
      "En la cima, la cadera queda paralela al suelo. Mantén 2 segundos.",
      "Baja controlado.",
    ],
    muscles: ["Glúteo mayor", "Glúteo medio", "Isquiotibiales", "Core"],
    imageUrl: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=700&q=80&fit=crop",
    safeForL5S1: true,
    notes: "Comenzar solo con peso corporal. No hiperextender la zona lumbar arriba.",
  },
  {
    id: "face-pull",
    name: "Face Pull",
    nameEs: "Jalón a la Cara",
    category: "strength",
    sets: 3,
    reps: 15,
    description: "Fortalece la espalda alta, mejora la postura y descarga la zona lumbar. Ideal con polea o banda.",
    steps: [
      "Fija una banda o polea a altura de cara.",
      "Sostén los extremos con ambas manos, pulgares hacia ti.",
      "Jala hacia tu cara abriendo los codos hacia los lados.",
      "Aprieta las escápulas al final del movimiento.",
      "Regresa controlado.",
    ],
    muscles: ["Deltoides posterior", "Trapecios", "Romboides", "Manguito rotador"],
    imageUrl: "https://images.unsplash.com/photo-1605296867304-46d5465a13f1?w=700&q=80&fit=crop",
    safeForL5S1: true,
  },
  {
    id: "farmer-carry",
    name: "Farmer Carry",
    nameEs: "Caminata del Granjero",
    category: "strength",
    sets: 3,
    duration: 35,
    description: "Uno de los mejores ejercicios de core funcional. Fortalece el transverso abdominal y la postura de forma natural.",
    steps: [
      "Sostén dos mancuernas o pesas a los costados.",
      "Pecho arriba, hombros atrás, abdomen firme.",
      "Camina recto a paso normal.",
      "Mantén el abdomen activo durante todo el recorrido.",
    ],
    muscles: ["Core completo", "Trapecios", "Antebrazos", "Glúteos", "Pantorrillas"],
    imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=700&q=80&fit=crop",
    safeForL5S1: true,
    notes: "Comenzar con pesas ligeras (5-10 kg cada mano). Nunca inclinar el torso.",
  },
  {
    id: "cat-cow",
    name: "Cat-Cow",
    nameEs: "Gato-Vaca",
    category: "mobility",
    sets: 2,
    reps: 10,
    description: "Moviliza la columna vertebral y activa los músculos estabilizadores de forma suave.",
    steps: [
      "En cuatro apoyos, espalda neutra.",
      "Exhala: arquea la espalda hacia arriba como un gato asustado.",
      "Inhala: baja la espalda y saca el pecho (posición vaca).",
      "Movimiento lento y fluido.",
    ],
    muscles: ["Erectores espinales", "Core profundo", "Dorsales"],
    imageUrl: "https://images.unsplash.com/photo-1575052814086-f385e2e2ad1b?w=700&q=80&fit=crop",
    safeForL5S1: true,
  },
  {
    id: "pelvic-tilt",
    name: "Pelvic Tilt",
    nameEs: "Inclinación Pélvica",
    category: "mobility",
    sets: 2,
    reps: 10,
    description: "Aprende a controlar la posición de la pelvis, clave para proteger L5-S1.",
    steps: [
      "Acostado boca arriba, rodillas dobladas.",
      "Contrae el abdomen y aplana la espalda baja contra el suelo.",
      "Mantén 5 segundos, libera.",
    ],
    muscles: ["Abdominales", "Glúteos", "Multífidos"],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=700&q=80&fit=crop",
    safeForL5S1: true,
  },
  {
    id: "thoracic-rotation",
    name: "Thoracic Rotation",
    nameEs: "Rotación Torácica",
    category: "mobility",
    sets: 2,
    reps: 10,
    description: "Mejora la movilidad de la espalda media, reduciendo compensación lumbar.",
    steps: [
      "En cuatro apoyos o sentado.",
      "Coloca la mano detrás de la cabeza.",
      "Rota el codo hacia el techo, siguiendo con la mirada.",
      "Rota hacia abajo y repite.",
    ],
    muscles: ["Rotadores torácicos", "Oblicuos", "Romboides"],
    imageUrl: "https://images.unsplash.com/photo-1602827686779-e28c5f07fbfb?w=700&q=80&fit=crop",
    safeForL5S1: true,
  },
];

// ─── Weekly Training Schedule ─────────────────────────────────────────────────
export const WEEKLY_SCHEDULE: TrainingDay[] = [
  {
    day: "lunes",
    type: "core",
    label: "Core + Movilidad",
    durationMin: 25,
    exercises: ["cat-cow", "pelvic-tilt", "thoracic-rotation", "bird-dog", "dead-bug", "glute-bridge", "side-plank"],
  },
  {
    day: "martes",
    type: "swimming",
    label: "Natación Técnica",
    durationMin: 30,
    swimmingSets: [
      { laps: 4, style: "warmup", note: "Calentamiento suave" },
      { laps: 8, style: "freestyle", note: "Ritmo zona 2: 105-122 bpm" },
      { laps: 4, style: "backstroke", note: "Activa glúteos, abre pecho" },
      { laps: 4, style: "kickboard", note: "Solo piernas, descarga lumbar" },
    ],
  },
  {
    day: "miercoles",
    type: "strength",
    label: "Fuerza Segura",
    durationMin: 25,
    exercises: ["hip-thrust", "face-pull", "farmer-carry", "bird-dog"],
  },
  {
    day: "jueves",
    type: "swimming",
    label: "Natación Cardio",
    durationMin: 35,
    swimmingSets: [
      { laps: 4, style: "warmup", note: "Calentamiento" },
      { laps: 10, style: "freestyle", note: "Cardio zona 2" },
      { laps: 6, style: "backstroke", note: "Recuperación activa" },
    ],
  },
  {
    day: "viernes",
    type: "swimming",
    label: "Natación Suave",
    durationMin: 25,
    swimmingSets: [
      { laps: 8, style: "freestyle", note: "Ritmo cómodo" },
      { laps: 4, style: "backstroke", note: "Descompresión" },
    ],
  },
  {
    day: "sabado",
    type: "swimming",
    label: "Natación Larga",
    durationMin: 45,
    swimmingSets: [
      { laps: 4, style: "warmup", note: "Calentamiento" },
      { laps: 12, style: "freestyle", note: "Volumen principal" },
      { laps: 6, style: "backstroke", note: "Estabilidad" },
      { laps: 4, style: "kickboard", note: "Terapéutico" },
    ],
  },
  {
    day: "domingo",
    type: "rest",
    label: "Descanso Activo",
    durationMin: 20,
  },
];

// ─── Nutrition menus A-B-C-D ──────────────────────────────────────────────────
export const WEEK_MENUS: WeekMenu[] = [
  {
    week: "A",
    days: [
      { day: "Lunes", desayuno: ["3 huevos revueltos", "½ aguacate", "1 tostada integral"], snack1: ["Manzana", "Yogurt griego"], almuerzo: ["Pollo a la plancha", "Arroz integral", "Brócoli al vapor", "Aceite de oliva"], snack2: ["Huevo cocido"], cena: ["Atún", "Aguacate", "Ensalada grande", "Tomate", "Pepino"], cenat: "keto" },
      { day: "Martes", desayuno: ["Avena cocida", "Yogurt griego", "Arándanos", "Nueces"], snack1: ["Pera", "Queso bajo grasa"], almuerzo: ["Salmón al horno", "Papa pequeña al horno", "Espinaca salteada"], snack2: ["Yogurt griego"], cena: ["Omelette de 3 huevos", "Champiñones", "Ensalada"], cenat: "convencional" },
      { day: "Miércoles", desayuno: ["Smoothie: proteína whey + banana + avena + leche de almendras"], snack1: ["Mandarina", "5 nueces"], almuerzo: ["Carne magra", "Arroz integral", "Ensalada grande"], snack2: ["Queso"], cena: ["Pollo desmechado", "Aguacate", "Verduras salteadas"], cenat: "keto" },
      { day: "Jueves", desayuno: ["2 huevos", "Avena", "Fruta de temporada"], snack1: ["Manzana", "Yogurt"], almuerzo: ["Pollo", "Lentejas", "Ensalada"], snack2: ["Huevo cocido"], cena: ["Pollo", "1 Arepa pequeña", "Ensalada"], cenat: "convencional" },
      { day: "Viernes", desayuno: ["3 huevos", "Espinaca", "Queso bajo grasa"], snack1: ["Pera", "Queso"], almuerzo: ["Pescado a la plancha", "Quinoa", "Verduras salteadas"], snack2: ["Yogurt griego"], cena: ["Atún", "Aguacate", "Ensalada"], cenat: "keto" },
      { day: "Sábado", desayuno: ["Avena", "Fruta", "Yogurt griego"], snack1: ["Frutos secos"], almuerzo: ["Carne magra", "Papa", "Ensalada"], snack2: ["Queso"], cena: ["Pollo", "1 Arepa", "Ensalada"], cenat: "convencional" },
      { day: "Domingo", desayuno: ["3 huevos", "Pan integral", "Aguacate"], snack1: ["Fruta + yogurt"], almuerzo: ["Pollo o pescado", "Arroz o papa", "Verduras"], snack2: ["Nueces"], cena: ["Cena ligera: yogurt + fruta"], cenat: "keto" },
    ],
  },
  {
    week: "B",
    days: [
      { day: "Lunes", desayuno: ["3 huevos", "Aguacate", "Café o té"], snack1: ["Yogurt + almendras"], almuerzo: ["Pollo salteado con verduras", "Arroz integral"], snack2: ["Queso"], cena: ["Ensalada + atún", "Aceite de oliva"], cenat: "keto" },
      { day: "Martes", desayuno: ["Avena", "Frutos rojos", "Proteína"], snack1: ["Manzana"], almuerzo: ["Salmón", "Quinoa", "Espárragos"], snack2: ["Yogurt griego"], cena: ["Tortilla de huevos + verduras"], cenat: "convencional" },
      { day: "Miércoles", desayuno: ["Smoothie proteína"], snack1: ["Mandarina + nueces"], almuerzo: ["Carne magra", "Arroz integral", "Ensalada"], snack2: ["Huevo cocido"], cena: ["Pollo + verduras"], cenat: "keto" },
      { day: "Jueves", desayuno: ["Huevos + fruta"], snack1: ["Queso pera"], almuerzo: ["Pescado", "Papa", "Ensalada"], snack2: ["Frutos secos"], cena: ["Ensalada + atún"], cenat: "convencional" },
      { day: "Viernes", desayuno: ["Omelette espinaca + queso"], snack1: ["Manzana + yogurt"], almuerzo: ["Pollo al horno", "Arroz integral", "Ensalada"], snack2: ["Yogurt griego"], cena: ["Sopa de verduras + atún"], cenat: "keto" },
      { day: "Sábado", desayuno: ["Avena + fruta + yogurt"], snack1: ["Nueces"], almuerzo: ["Carne magra", "Papa", "Verduras"], snack2: ["Queso"], cena: ["Ensalada + pescado"], cenat: "convencional" },
      { day: "Domingo", desayuno: ["Huevos + pan integral + aguacate"], snack1: ["Fruta + queso"], almuerzo: ["Proteína + arroz o papa + verduras"], snack2: ["Yogurt"], cena: ["Cena ligera: yogurt + fruta + nueces"], cenat: "keto" },
    ],
  },
  {
    week: "C",
    days: [
      { day: "Lunes", desayuno: ["Avena + proteína whey"], snack1: ["Manzana + queso"], almuerzo: ["Pescado + arroz integral + verduras"], snack2: ["Huevo cocido"], cena: ["Carne + ensalada"], cenat: "keto" },
      { day: "Martes", desayuno: ["3 huevos revueltos + queso"], snack1: ["Yogurt griego + frutos rojos"], almuerzo: ["Pollo + lentejas + ensalada"], snack2: ["Nueces"], cena: ["Pollo + 1 arepa + ensalada"], cenat: "convencional" },
      { day: "Miércoles", desayuno: ["Smoothie: proteína + banana + avena"], snack1: ["Pera + queso"], almuerzo: ["Salmón + papa + espinaca"], snack2: ["Yogurt"], cena: ["Atún + aguacate + ensalada"], cenat: "keto" },
      { day: "Jueves", desayuno: ["2 huevos + avena + fruta"], snack1: ["Mandarina + nueces"], almuerzo: ["Carne magra + arroz + ensalada"], snack2: ["Queso"], cena: ["Pollo + arepa + ensalada"], cenat: "convencional" },
      { day: "Viernes", desayuno: ["Omelette 3 huevos + champiñones"], snack1: ["Fruta + yogurt"], almuerzo: ["Pescado a la plancha + quinoa + verduras"], snack2: ["Huevo cocido"], cena: ["Carne + ensalada + aguacate"], cenat: "keto" },
      { day: "Sábado", desayuno: ["Avena + fruta + yogurt"], snack1: ["Frutos secos"], almuerzo: ["Pollo + arroz + brócoli"], snack2: ["Yogurt griego"], cena: ["Ensalada + pescado"], cenat: "convencional" },
      { day: "Domingo", desayuno: ["3 huevos + aguacate + tostada integral"], snack1: ["Fruta + queso"], almuerzo: ["Pollo o carne + papa o arroz + verduras"], snack2: ["Nueces"], cena: ["Cena ligera: yogurt + fruta"], cenat: "keto" },
    ],
  },
  {
    week: "D",
    days: [
      { day: "Lunes", desayuno: ["3 huevos + queso bajo grasa"], snack1: ["Fruta + yogurt griego"], almuerzo: ["Pollo + lentejas + ensalada grande"], snack2: ["Nueces"], cena: ["Pescado + aguacate"], cenat: "keto" },
      { day: "Martes", desayuno: ["Avena + yogurt + arándanos"], snack1: ["Manzana + mantequilla de maní"], almuerzo: ["Carne magra + arroz integral + ensalada"], snack2: ["Huevo cocido"], cena: ["Pollo + 1 arepa + ensalada"], cenat: "convencional" },
      { day: "Miércoles", desayuno: ["Smoothie proteína + banana + leche almendras"], snack1: ["Pera + queso"], almuerzo: ["Pescado + quinoa + verduras salteadas"], snack2: ["Yogurt"], cena: ["Atún + aguacate + ensalada"], cenat: "keto" },
      { day: "Jueves", desayuno: ["3 huevos + espinaca + queso"], snack1: ["Mandarina + 5 nueces"], almuerzo: ["Pollo al horno + arroz integral + ensalada"], snack2: ["Yogurt griego"], cena: ["Sándwich de pollo en pan integral"], cenat: "convencional" },
      { day: "Viernes", desayuno: ["2 huevos + avena + fruta"], snack1: ["Manzana + yogurt"], almuerzo: ["Salmón + papa + espinaca salteada"], snack2: ["Queso"], cena: ["Carne + ensalada + aceite de oliva"], cenat: "keto" },
      { day: "Sábado", desayuno: ["Omelette 3 huevos + queso + tomate"], snack1: ["Frutos secos"], almuerzo: ["Pescado + pasta integral + ensalada"], snack2: ["Nueces"], cena: ["Pollo + arepa + ensalada"], cenat: "convencional" },
      { day: "Domingo", desayuno: ["Huevos + pan integral + aguacate"], snack1: ["Fruta + yogurt"], almuerzo: ["Proteína flexible + arroz o papa + verduras"], snack2: ["Queso"], cena: ["Cena ligera: yogurt + fruta + nueces"], cenat: "keto" },
    ],
  },
];

// ─── Progress projections ─────────────────────────────────────────────────────
export const WEIGHT_PROJECTIONS = [
  { week: 1, weight: 110 }, { week: 2, weight: 109.3 },
  { week: 3, weight: 108.5 }, { week: 4, weight: 107.5 },
  { week: 5, weight: 106.5 }, { week: 6, weight: 105.8 },
  { week: 7, weight: 104.8 }, { week: 8, weight: 103.8 },
  { week: 9, weight: 103 }, { week: 10, weight: 102 },
  { week: 11, weight: 101 }, { week: 12, weight: 100 },
];

export const SWIMMING_PROJECTIONS = [
  { week: 1, meters: 1200 }, { week: 2, meters: 1350 },
  { week: 3, meters: 1500 }, { week: 4, meters: 1650 },
  { week: 5, meters: 1800 }, { week: 6, meters: 2000 },
  { week: 7, meters: 2200 }, { week: 8, meters: 2400 },
  { week: 9, meters: 2600 }, { week: 10, meters: 2800 },
  { week: 11, meters: 3000 }, { week: 12, meters: 3200 },
];

export const HEART_RATE_ZONES = {
  max: 175,
  zone2Min: 105,
  zone2Max: 122,
  age: 45,
};

export const USER_PROFILE = {
  name: "Jaime",
  age: 45,
  height: 180,
  weightStart: 110,
  weightGoalMonth1: 105,
  weightGoalMonth2: 101,
  weightGoalMonth3: 97,
  condition: "Espondilolistesis L5-S1",
  proteinGoal: 157,
  waterGoal: 2,
  programStartDate: "2026-03-16",
};
